### PR TITLE
Introduce 'prefetch-src'. Closes w3c/webappsec-csp#107.

### PR DESCRIPTION
**Pull request by mikewest**
@yoavweiss, @annevk, @andypaicu: WDYT?

/cc @dveditz, @ckerschb

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/pull/283.html" title="Last updated on Jan 15, 2018, 2:18 PM GMT (78ac5e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/283/7a4577c...78ac5e8.html" title="Last updated on Jan 15, 2018, 2:18 PM GMT (78ac5e8)">Diff</a>

### CODE REVIEW

**Comment by mikewest** [comment]
(For clarity: tests are coming in a subsequent patch once I figure out how prefetch works in Chrome :) )

**Comment by yoavweiss** [comment]
Looks good, but I don't know enough about CSP's mechanics to approve.

**Comment by annevk** [comment]
In https://github.com/whatwg/fetch/pull/659 it's an initiator as per discussion in https://github.com/whatwg/fetch/issues/658, in particular https://github.com/whatwg/fetch/issues/658#issuecomment-355913784.

**Comment by annevk** [comment]
So should Fetch still distinguish prerender and prefetch? It seems slightly cleaner to give them distinct initiators, even if they end up with the same path here.

**Comment by mikewest** [comment]
Happy to defer that to @yoavweiss. The CSP integration should be straightforward either way.

**Comment by yoavweiss** [comment]
> It seems slightly cleaner to give them distinct initiators, even if they end up with the same path here.

Agree that it does seem cleaner.

**Comment by annevk** [comment]
@yoavweiss can you update https://github.com/whatwg/fetch/pull/659 so it lists both?

**Comment by yoavweiss** [comment]
> @yoavweiss can you update whatwg/fetch#659 so it lists both?

updated. Also filed https://github.com/whatwg/html/pull/3353

**Comment by mikewest** [comment]
Updated this patch as well. WDYT?

Tests for `prefetch` are in https://github.com/w3c/web-platform-tests/pull/9013, feedback welcome. I can add tests for `prerender` as well, but Chrome won't pass them until @yoavweiss makes the events work. :)

**Comment by yoavweiss** [comment]
> I can add tests for prerender as well, but Chrome won't pass them until @yoavweiss makes the events work. :)

Looked into the Chrome prerender onload event [issues](https://bugs.chromium.org/p/chromium/issues/detail?id=801588), and they seem to be related to NoStatePrefetch and to the fact that prerender triggers a proprietary event, rather than the standard `load` one. I'm happy to fix the standard event bits, but hoping the NoStatePrefetch folks can fix the part that's on their end :)

In the mean time it seems fine to add a test that fails, and which hopefully work once implementations are fixed.

**Comment by mikewest** [comment]
> In the mean time it seems fine to add a test that fails, and which hopefully work once implementations are fixed.

Yeah. I mean, we'll skip it because otherwise it will just timeout because we have no idea when to stop without an event, and I don't want to add several seconds to every test run. But we'll unskip it once it works! :)

**Comment by annevk** [comment]
I'm happy with this. (And for clarity this means we'll tackle dns-prefetch et al in a separate PR.)

**Comment by mikewest** [comment]
> And for clarity this means we'll tackle dns-prefetch et al in a separate PR.

Correct. This is just `prefetch-src`; those will fall out of a different set of constraints (and I have no idea where they're defined... @yoavweiss?)

**Pull request merged**
