### PR TITLE
Change to "main" branch in Version History link

### PR DESCRIPTION
**Pull request by sideshowbarker**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/pull/467.html" title="Last updated on Feb 19, 2021, 10:52 AM UTC (e6505f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/467/a036e31...e6505f0.html" title="Last updated on Feb 19, 2021, 10:52 AM UTC (e6505f0)">Diff</a>

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Might be good to adopt the Meta: / Editorial: convention from WHATWG.

**Comment by annevk** [comment]
In WHATWG we also tend to link to https://github.com/w3c/webappsec-csp/commits, but I guess that is a lot less clean here...

**Comment by sideshowbarker** [comment]
> Might be good to adopt the Meta: / Editorial: convention from WHATWG.

Good point. Added `Meta:` to this one

**Comment by sideshowbarker** [comment]
> In WHATWG we also tend to link to [w3c/webappsec-csp/commits](https://github.com/w3c/webappsec-csp/commits), but I guess that is a lot less clean here...

Yeah, I think here for now at least the most user-friendly thing is to restrict it to the index.src.html file

**Pull request merged**
