### PR TITLE
Fix typo in CSP3 spec

### PR DESCRIPTION
**Pull request by romainneutron**

### CODE REVIEW

**Comment by romainneutron** [comment]
I'm not sure how to solve the ipr issue, Should I add `+@romainneutron` somewhere?

**Comment by mikewest** [comment]
@wseltzer might be able to help with that in general. For this specific patch, you're correcting typos in two non-normative notes. I can't imagine that exposes us to any intellectual property risk.

**Comment by mikewest** [comment]
Thanks!

**Comment by wseltzer** [comment]
@romainneutron Happy to talk with you about W3C participation if you're interested in contributing more. I'll ping you off-thread.

**Pull request merged**
