### PR TITLE
Some smaller wording nits

### PR DESCRIPTION
**Pull request by jonathanKingston**
- Changed the report-to urls
- Changed `,` to `;` in example
- Added missing semicolons
- Change formatting of quoting

Let me know if there are any issues etc, thanks

### CODE REVIEW

**Comment by mikewest** [comment]
@wseltzer: Here too?

**Comment by mikewest** [comment]
If you rebase this onto tip-of-tree, I'm happy to merge it.

**Comment by jonathanKingston** [comment]
@mikewest rebased :package: :smile:

**Comment by wseltzer** [comment]
@mikewest all set

**Comment by mikewest** [comment]
Thanks!

**Pull request merged**
