### PR TITLE
Add support for the webidentity destination

### PR DESCRIPTION
**Pull request by cbiesinger**
This is being added to fetch in https://github.com/whatwg/fetch/pull/1495

See also issue fedidcg/FedCM#353 and fedidcg/FedCM#320

Tests are in https://github.com/web-platform-tests/wpt/blob/master/credential-management/fedcm-network-requests.sub.https.html#L139

### CODE REVIEW

**Comment by cbiesinger** [comment]
I don't understand the failed check, can someone explain...?

**Comment by clelland** [comment]
```
$ java -jar "/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/vnu-jar/build/dist/vnu.jar" --also-check-css index.html
"file:/home/runner/work/webappsec-csp/webappsec-csp.w3c/index.html":19.323-19.323: error: CSS: “content”: Parse Error.
```

Yeah, that does not appear related to the PR at all. I'd suspect an upstream issue with the build tools; a re-run didn't change anything, so it doesn't appear to be a transient issue.

**Review by mikewest — APPROVED** [review]
LGTM. I'll land this once the Fetch PR lands.

**Comment by antosart** [comment]
The failed check should be fixed by #569.

**Comment by cbiesinger** [comment]
Thanks! Looks like the fetch PR has landed now.

**Pull request merged**
