### PR TITLE
Specify the type of empty strings are

### PR DESCRIPTION
**Pull request by arichiv**
#591

This seems more correct.

### CODE REVIEW

**Review by annevk — APPROVED** [review]
Thanks!

**Comment by arichiv** [comment]
The build failure looks unrelated but I assume it won't properly push the update until it's fixed. Should I go ahead and do so on another PR? Not sure if there's a maintainer who I should tag on a task instead

**Comment by annevk** [comment]
If it's a minor thing you could push it here. Up to you.

**Comment by mikewest** [comment]
Thanks!

**Comment by mikewest** [comment]
(I'll fix the build error in a subsequent patch.)

**Pull request merged**
