### PR TITLE
Implement 'HostEnsureCanCompileStrings'.

### PR DESCRIPTION
**Pull request by mikewest**
@annevk, @domenic: Can you take a look at this attempt to address the CSP side of https://github.com/whatwg/html/issues/271#issuecomment-198084014?

### CODE REVIEW

**Comment by mikewest** [comment]
@wseltzer: According to the IPR checker, I'm not allowed to contribute to W3C specs. *cough* Perhaps you could poke at that? :)

**Comment by domenic** [comment]
Didn't we vaguely discuss using both callerRealm and calleeRealm?

**Comment by mikewest** [comment]
I don't recall. The caller realm seems most important, but we could check both, I guess?

**Comment by domenic** [comment]
Yeah, it seems like you shouldn't be able to do `cspedWindow.eval('...')` to me. Both would be nice.

**Comment by mikewest** [comment]
Changed to use both in https://github.com/w3c/webappsec-csp/commit/8d3e743d291a25fd6f116dd9cc487f06f0e25104.

**Comment by wseltzer** [comment]
@mikewest fixed the ipr check bug

**Pull request merged**
