### PR TITLE
Inherit source browsing context's CSP instead of parent/opener

### PR DESCRIPTION
**Pull request by andypaicu**
Fixes https://github.com/w3c/webappsec-csp/issues/209
Fixes https://github.com/w3c/webappsec-csp/issues/211

***
<a href="https://pr-preview.s3.amazonaws.com/andypaicu/webappsec-csp/pull/358.html" title="Last updated on Nov 7, 2018, 10:48 AM GMT (1068f9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/358/df35fe4...andypaicu:1068f9a.html" title="Last updated on Nov 7, 2018, 10:48 AM GMT (1068f9a)">Diff</a>

### CODE REVIEW

**Comment by andypaicu** [comment]
ccing @bzbarsky as he raised the issues

**Comment by andypaicu** [comment]
This also requires a change to the HTML spec.

**Comment by bzbarsky** [comment]
Thank you for working on this!

Unfortunately, the proposed changes are introducing a security issue (like almost any use of "active document" on a browsing context does).

Specifically, consider the case when a load (call it L) is started by script running in in some window at origin  A, which then proceeds to navigate its browsing context to origin B.   Since the loads are independent of each other, the load of B can complete before we do "Initialize a Document 's CSP list" on the Response generated by L.  At that point "source's active document" will be B, and we will pick up CSP from there.  But we should be picking up CSP from **A** in this case, I would think.

This is actually a preexisting security bug in https://w3c.github.io/webappsec-csp/#should-block-navigation-response as far as I can tell: the algorithms under there end up grabbing the CSP from the active document of _source_ which may be completely unrelated to who started the load...  Not sure why they're doing that.  Do browsers actually implement what the spec says here?  I really hope not...

Anyway, in terms of fixing this, if we have the Request available we could presumably grab the CSP from the request's [**client**](https://fetch.spec.whatwg.org/#concept-request-client).  Though there is an open question as to whether the CSP should be snapshotted at the point when we are processing the response or at the point when we create the request.... Again, what do browsers currently implement?

**Comment by andypaicu** [comment]
Thank you for pointing out the security issue.

When it comes to navigations, chrome takes a snapshot of the CSP at request time (for verification purposes) but I'm pretty sure when it comes to inheriting the CSP it uses whatever the current CSP is.  This is for technical/architecture reasons. So the verification CSP and the inherited CSP could be different.

In practice I doubt the request/response distinction matters too much. In practice CSP is pretty much always set up as early as possible. Also you can't relax CSP, only add more restrictive CSP by adding more `<meta http-equiv` headers so adding more CSP between a request and a response doesn't seem to open any vulnerability to me.

I think your suggestion of using the request's client is good (though my opinion on this is close to null, perhaps other people with more knowledge can weigh in here?). Considering this is already an existing issue I have raised a separate [bug](https://github.com/w3c/webappsec-csp/issues/360) and I would like to treat it as orthogonal to this PR.

**Comment by bzbarsky** [comment]
> In practice I doubt the request/response distinction matters too much

Well, it matters in that you can end up with loads being blocked if you snapshot on Response  processing that would not have been blocked if you snapshot on Request creation.  If different UAs do different things here, that would lead to interop problems.  Seems to me like we should make sure this is defined, tested, and browser bugs filed as needed.

> adding more CSP between a request and a response doesn't seem to open any vulnerability to me

Sure.  The Request vs Response thing is an interop problem, not a security problem.

> I would like to treat it as orthogonal to this PR

I am OK with that if we include an explicit note in the spec that points out that it's known to be wrong and links to the other issue.  That will hopefully  avoid implementors implementing the spec as-is and creating security holes in websites in the process while the spec around this gets sorted out.

**Comment by andypaicu** [comment]
I've added an `ISSUE:` line

**Comment by andypaicu** [comment]
@mikewest PTAL

**Comment by andypaicu** [comment]
A corresponding HTML PR is coming very soon. I didn't want to start it before I'm sure that this PR passes because there was a risk of having to redo depending on feedback.

**Pull request merged**
