### PR TITLE
Typo fix: ancilliary->ancillary

### PR DESCRIPTION
**Pull request by terriko**

### CODE REVIEW

**Comment by terriko** [comment]
Not sure why I'm showing up as an unknown user.  If there's something I need to do on my end to make sure the w3c knows what github account is me, let me know.  (it's already in my w3c user profile which was all my AC rep asked me to do.)

**Comment by mikewest** [comment]
@wseltzer, can you fix @terriko's account via some secret W3C magic?

**Comment by mikewest** [comment]
(I'm merging this without waiting, as it's fairly clear that Terri is awesome enough to commit. :) )

**Comment by wseltzer** [comment]
@mikewest, @terriko thanks, added to the system!

**Pull request merged**
